### ISSUE TITLE
Trouble getting time stretching example working

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#1]
Let me preface by saying I'm not too versed in JS so perhaps this is super obvious...

I copied the contents of example_timestretching and superpowered.js to my server, and I get the following error upon pressing the 'Start' button:
```

superpowered.js:8 Uncaught TypeError: Cannot read property 'addModule' of undefined
    at Object.Module.createAudioNode (superpowered.js:8)
    at HTMLButtonElement.start (main.js:87)
Module.createAudioNode @ superpowered.js:8
```
It appears the audioContext object does not have a audioWorklet property while running on my server, while if I debug on the running example on the Superpowered server, it does, and the example works.

This is desktop Chrome.

**Comment by gaborszanto** [comment]
Is it possible that you are not using "localhost" or https? Audio Worklets only work on https by the W3C standard.

**Comment by svenoaks** [comment]
Oh, I got it working on localhost, I was trying on http before. I assume it will work fine on https.
