### ISSUE TITLE
Example for playing multiple sounds and/or tracks

### ISSUE THREAD

**Issue by designbyadrian** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#16]
Hello,

Is there any example you could provide for playing multiple simultaneous sounds and/or tracks? Something that looks like a mini piano would be really helpful!

I'm trying to have one global audio context, then connecting multiple audio nodes to it. Each process has its own player object. I get no errors, but also no sound.

If you're curious about where I'm doing something wrong, here's the gist of it (pun intended): https://gist.github.com/designbyadrian/947d4090bea34b4aff498cf09f0d7711

**Comment by designbyadrian** [comment]
As a side note, if I've got more than ten different sounds I'd like to trigger, is it better to concatenate them into one file, then play using `play([MEMORY LOCATIONI])`?

**Comment by gaborszanto** [comment]
Create on node only, and put all your audio processing code inside that single node, just like in the examples. To support multiple simultaneous sounds, just create that many AdvancedAudioPlayers.

**Comment by designbyadrian** [comment]
I'm still having trouble with this. The problem lies with the processAudio function. Without it, I just get a loud noise. With it... well, I don't know how to process multiple tracks at once.

I'm using your time stretching example: https://gist.github.com/designbyadrian/5ecb91fe3cc2cac49911dc178d1fef36

**Comment by logesh2496** [comment]
@designbyadrian i'm into the same situation. things are fine with just one player. 
Were you able to solve the issue?- How do I handle the silence in processAudio when multiple players are created?

I also got into an another issue, i couldn't use setPosition() with three different position. Things work quite well with just two new positions at different intervals. But if i call the setPosition with third new valule(ms), the audio is stopped.

Thanks

**Comment by designbyadrian** [comment]
@logesh2496 No, I'm clueless. In my humble opinion, more examples should be provided for developers who don't come from iOS/Android.
