### ISSUE TITLE
Cannot reach bottom of TOC in the docs without scrolling to bottom

### ISSUE THREAD

**Issue by designbyadrian** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#17]
It's not possible to see the entire contents of Superpowered Javascript SDK without scrolling to the bottom of the entire page.

**Steps to reproduce:**

1. Use a screen that's 15" or less
2. Visit https://superpowered.com/js-wasm-sdk/docs.html
3. Move pointer to the sidebar with the headings, try to scroll to bottom.

**Expected results:**

Sidebar is scrolled, revealing the headings further down

**Actual results:**

Whole page is scrolled, except the sidebar.

**Comment by gaborszanto** [comment]
fixed
