### ISSUE TITLE
react js example to get access a micrphone

### ISSUE THREAD

**Issue by muccurly** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#26]
./src/superpowered/SuperpoweredTrackLoaderModule.js
  Line 41:42:  'define' is not defined                   no-undef
  Line 41:57:  Expected imports instead of AMD define()  import/no-amd
  Line 41:57:  'define' is not defined                   no-undef

Hi there, I got this error, maybe I did smth incorrectly, do u have an example for react.js?

**Comment by petermlyon** [comment]
Just drop `superpowered/` into your public folder and then include the files as external scripts in your react app, something like [](https://stackoverflow.com/questions/53396307/how-do-i-use-external-script-that-i-add-to-react-js).
