### ISSUE TITLE
Firefox using ScriptProcessorNode

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#3]
Firefox on MacOS (haven't verified other OS yet) is using ScriptProcessorNode instead of AudioWorklet. Is this intended behavior?

**Comment by gaborszanto** [comment]
We have absolutely no control on what web browsers implement: https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode

**Comment by svenoaks** [comment]
Ok, I guess FireFox hasn't implemented AudioWorkletNode yet.
