### ISSUE TITLE
ERR_TIMED_OUT when trying to fetch the license

### ISSUE THREAD

**Issue by tareqdayya** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#38]
Hello 👋🏻

While instantiating the superpowered instance, it fails to fetch the license `https://superpowered.com/license/.../wasm.txt`.  We get an `ERR_TIMED_OUT` error.

Before having this problem, the license used to, sometimes, fail to fetch with a `ERR_CONNECTION_REFUSED`. Since this morning, however, the license fails to fetch completely.

Thanks

**Comment by dodds-cc** [comment]
Hi there @tareqdayya Apologies that you experienced issues there, we did have an issue with the backend temporarily. We took some steps a while back to stabilise the license endpoint. We've not seen or had reports of any failure for a while now so will close this ticket for now
