### ISSUE TITLE
Superpowered license key response fails due to CORS policy

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#8]
I changed the license key to the key shown in the Superpowered dev site, and I get the following error response:
![Screenshot from 2020-01-03 18-00-58](https://user-images.githubusercontent.com/5206058/71755032-d4c58100-2e56-11ea-8db8-14ece4962d6a.png)

I believe the response from Superpowered site is missing a header.

**Comment by gaborszanto** [comment]
Please try it now and let me know.

**Comment by svenoaks** [comment]
fixed, thanks.
