### ISSUE TITLE
Throw error instead of showing alert

### ISSUE THREAD

**Issue by RicherStAmand** [superpoweredSDK/web-audio-javascript-webassembly-SDK-interactive-audio#9]
It appears the `superpowered` module and `superpowered-worker` modules call `alert` when license keys fail. This is a very agressive user interaction, and a preferable pattern would be to throw an error instead so developers can choose how to handle the failure.

If there are other areas in the library where alerts are invoked, they should ideally also be changed to errors. Thank you!

**Comment by gaborszanto** [comment]
Correct, Superpowered displays an alert when the license key is not valid or suspended. There are no other areas where it may happen.

This is exactly how we designed it, to be very obvious that there is a license violation. We prefer this solution over a console error or any other "softer" mechanism.
